Structures Data: NumPy's Structures Arrays

In [1]:
import numpy as np

In [7]:
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

In [8]:
x = np.zeros(4, dtype=int)

In [9]:
data = np.zeros(4, dtype={'names': ('name', 'age', 'weight'),
                          'formats': ('U10', 'i4', 'f8')})
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


In [10]:
# U10: unicode string of maximum length 10
# i4: 4-byte (32-bit) integer
# f8: 8-byte (64 bit) float

In [12]:
data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)

[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]


In [13]:
# Get all names
data['name']

array(['Alice', 'Bob', 'Cathy', 'Doug'], dtype='<U10')

In [14]:
# Get first row of data
data[0]

('Alice', 25, 55.)

In [17]:
data[-1]['name']

'Doug'

In [18]:
data[data['age'] < 30]['name']

array(['Alice', 'Doug'], dtype='<U10')

Creating structured arrays

In [20]:
np.dtype({'names':('name', 'age', 'weight'),
          'formats':('U10', 'i4', 'f8')})

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [21]:
np.dtype({'names':('name', 'age', 'weight'),
          'formats':((np.str_, 10), int, np.float32)})

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [22]:
np.dtype([('name', 'S10'), ('age', 'i4'), ('weight', 'f8')])

dtype([('name', 'S10'), ('age', '<i4'), ('weight', '<f8')])

In [23]:
np.dtype('S10,i4,f8')

dtype([('f0', 'S10'), ('f1', '<i4'), ('f2', '<f8')])

More advanced compound types

In [24]:
tp = np.dtype([('id', 'i8'), ('mat', 'f8', (3, 3))])
X = np.zeros(1, dtype=tp)
print(X[0])
print(X['mat'][0])

(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


RecordArrays: Structured arrays with a twist

In [25]:
data['age']

array([25, 45, 37, 19])

In [26]:
data_rec = data.view(np.recarray)
data_rec.age

array([25, 45, 37, 19])

In [27]:
%timeit data['age']
%timeit data_rec['age']
%timeit data_rec.age

159 ns ± 11.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
3.06 µs ± 143 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
4.26 µs ± 89.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
