In [2]:
!pip install numpy # para instalarlo por primera vez

In [6]:
import numpy as np

In [4]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [8]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [9]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [10]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
# Create a 3x5 floating-point array filled with 1s
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [13]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [15]:
np.random.random((3, 3))

array([[0.35294034, 0.08112011, 0.90082198],
       [0.21499918, 0.91225802, 0.70763636],
       [0.86491155, 0.154664  , 0.57614202]])

In [16]:
np.random.normal(0, 10, (3, 3))

array([[10.08243665, 15.14266221, -1.87834533],
       [11.30309554,  7.35578513,  0.04140414],
       [10.94881463, 15.17294887, 11.29908711]])

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.empty(3)

array([1., 1., 1.])

Atributos de NumPy

In [19]:
np.random.seed(0)

x1 = np.random.randint(10, size=6) # una dimensión
x2 = np.random.randint(10, size=(3, 4)) # dos dimensiones
x3 = np.random.randint(10, size=(3, 4, 5)) # tres dimensiones

In [22]:
print("el número de dimensiones de x3 es:", x3.ndim)
print("el tamaño de cada dimensión de x3 es:", x3.shape)
print("el tamaño total del arregloo es:", x3.size)

el número de dimensiones de x3 es: 3
el tamaño de cada dimensión de x3 es: (3, 4, 5)
el tamaño total del arregloo es: 60


In [24]:
print("dtype:", x3.dtype)

dtype: int32


In [25]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 4 bytes
nbytes: 240 bytes


In [26]:
x1

array([5, 0, 3, 3, 7, 9])

In [27]:
x1[0]

5

In [28]:
x1[-1]

9

In [29]:
x2[2, 0]

1

In [30]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [31]:
x1[0] = 3.14159 # el resultado se redondea
x1

array([3, 0, 3, 3, 7, 9])

In [40]:
x = np.arange(10)

In [41]:
x[:5]

array([0, 1, 2, 3, 4])

In [42]:
x[5:]

array([5, 6, 7, 8, 9])

In [43]:
x[4:7]

array([4, 5, 6])

In [44]:
x[::2]

array([0, 2, 4, 6, 8])

In [45]:
x[1::2]

array([1, 3, 5, 7, 9])

In [46]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [47]:
x2[:2, :3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [48]:
x2[:3, ::2]

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [49]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [50]:
print(x2[:, 0])

[12  7  1]


In [51]:
print(x2[0, :])

[12  5  2  4]


In [52]:
print(x2[0])

[12  5  2  4]


Subarrays as no-copy views

In [53]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [55]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [56]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [57]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


Creating copies of arrays

In [59]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [60]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [61]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


Reshaping of Arrays

In [62]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [64]:
x = np.array([1, 2, 3])

x.reshape((1, 3))

array([[1, 2, 3]])

In [65]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [67]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [68]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [69]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

Array Concatenation and splitting

In [70]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [71]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [73]:
grid = np.array([[1, 2, 3],
               [4, 5, 6]])
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [74]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [75]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                [6, 5, 4]])
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [76]:
y = np.array([[99],
             [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [79]:
a = np.array((1,2,3))
b = np.array((2,3,4))
np.dstack((a,b))

array([[[1, 2],
        [2, 3],
        [3, 4]]])

In [80]:
a = np.array([[1],[2],[3]])
b = np.array([[2],[3],[4]])
np.dstack((a,b))

array([[[1, 2]],

       [[2, 3]],

       [[3, 4]]])

In [81]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [83]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [84]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [85]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
